services:
  - type: web
    name: reconcraft-api
    env: python
    buildCommand: "./build.sh && pip install -r requirements.txt"
    startCommand: gunicorn routes:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: RECON_API_KEY
        value: myapikey
      - key: PYTHON_VERSION
        value: "3.11"
    autoDeploy: true
