services:
  - type: web
    name: reconcraft-api
    env: python
    buildCommand: "./build.sh"
    startCommand: gunicorn routes:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key:  RECON_API_KEY
        value: myapikey
      - key: PATH
        value: "/opt/render/project/.gopath/bin:/opt/render/project/.venv/bin:/usr/local/bin:/usr/bin:/bin"
    autoDeploy: true
