services:
  - type: web
    name: reconcraft-api
    env: python
    buildCommand: "./build.sh"
    startCommand: gunicorn routes:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key:  RECON_API_KEY
        value: myapikey
    autoDeploy: true
